name: Upload documentation

on:
  workflow_run:
    workflows: ["Run tests"]
    branches: ["main"]
    types:
      - completed


jobs:
  run_sphinx:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build sphinx
    steps:
      - name: Download sphinx artifact
        uses: actions/download-artifact@v3
        with:
          name: sphinx-build
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/build/
