name: Upload documentation

on:
  workflow_call:
    branches:
      - "main"

jobs:
  run_sphinx:
    runs-on: ubuntu-latest
    name: Build sphinx
    steps:
      - name: Download sphinx artifact
        uses: actions/download-artifact@v3
        with:
          name: sphinx-build
          path: sphinx/
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v2
        with:
          path: sphinx/
