name: Run tests


on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installation
        run: pip install .[dev]
      - name: Run tests
        env:
          BARENTSWATCH_CLIENT_ID: ${{ secrets.BARENTSWATCH_CLIENT_ID }}
          BARENTSWATCH_CLIENT_SECRET: ${{ secrets.BARENTSWATCH_CLIENT_SECRET }}
        run: pytest
      - name: Run sphinx html build
        run: sphinx-build -v -b html -W --keep-going -n ./docs/source/ ./docs/build/
      - name: Run sphinx doctest
        run: sphinx-build -M doctest ./docs/source/ ./docs/build/
      - name: Run sphinx linkcheck
        run: sphinx-build -M linkcheck ./docs/source/ ./docs/build/
      - name: Upload sphinx artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-build
          path: docs/build/
          retention-days: 1
